apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: app1
spec:
  chart: ./charts/app1
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 5m