apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app1
spec:
  releaseName: app1
  chart:
    spec:
      chart: app1
      sourceRef:
        kind: HelmChart
        name: app1
  interval: 5m
  install:
    remediation:
      retries: 3