apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: default-secretstore
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      server:
        caProvider:
          namespace: "default"
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets