apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 'v1.3.2'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  interval: 5m
  install:
    remediation:
      retries: 3