---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app1
  namespace: app1
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./apps/app1"
  prune: true
  timeout: 1m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: test1