---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./apps/podinfo"
  prune: true
  timeout: 1m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: test1
        # Fail if this Secret does not exist.